services:
  claude-dev:
    container_name: ${COMPOSE_PROJECT_NAME:-claude-dev}
    build:
      context: .
      additional_contexts:
        ssh_config: ${HOME}/.ssh
      args:
        CODE_PATH: ${CODE_PATH}
        USERNAME: ${USER}
        USER_HOME: ${HOME}
        SSH_AUTHORIZED_KEYS: ${SSH_AUTHORIZED_KEYS}
    user: '${USER}'
    ports:
      - "${SSH_PORT:-2222}:22"
    volumes:
      - ${CODE_PATH}:${CODE_PATH}
      - ${HOME}/.claude:${HOME}/.claude
      - ${HOME}/.claude.json:${HOME}/.claude.json
      - ssh-host-keys:/etc/ssh
      - type: bind
        source: ${HOME}/.gitconfig
        target: ${HOME}/.gitconfig
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${HOME}/.gitignore
        target: ${HOME}/.gitignore
        read_only: true
        bind:
          create_host_path: false

    command: >
      sh -c "
        if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
          sudo cp -r /etc/ssh.original/. /etc/ssh/
          sudo ssh-keygen -A
        fi
        sudo /usr/sbin/sshd -D
      "

    restart: always

volumes:
  ssh-host-keys:
