services:
  claude-dev:
    container_name: claude-dev
    build:
      context: .
      args:
        CODE_PATH: ${CODE_PATH}
        USERNAME: ${USERNAME}
    user: '${USERNAME}'
    ports:
      - "2222:22"       # SSH into the container on port 2222
    volumes:
      - ${CODE_PATH}:${CODE_PATH}
      - ./data/home:/home/${USERNAME}/
      - ${HOME}/.claude:/home/${USERNAME}/.claude
      - ${HOME}/.claude.json:/home/${USERNAME}/.claude.json
      - ./data/ssh:/etc/ssh                      # persist SSH host keys across rebuilds

    command: >
      sh -c "
        if [ ! -f /etc/ssh/sshd_config ]; then
          sudo cp -r /etc/ssh.original/. /etc/ssh/
          sudo ssh-keygen -A
        fi
        sudo /usr/sbin/sshd -D
      "
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: always
